name: CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonacion del codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Compilacion
        run: |
          mvn package

      - name: Test Unitarios
        run: mvn test
      
      - name: Setup Java JDK para SC
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: SonarCloud Scan
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{secrets.SONAR_TOKEN}} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=lmirandal\
          -Dsonar.projectKey=lmirandal_microservicio-java
