name: CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonacion del codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Compilacion
        run: |
          mvn package

      - name: Test Unitarios
        run: mvn test
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: SonarCloud Scan
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{secrets.SONAR_TOKEN}} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=lmirandal\
          -Dsonar.projectKey=lmirandal_microservicio-java

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: Mostrar SonarQube Quality Gate Status
        run: echo "El status es ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: gode23
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        run: |
          docker build -t gode23/microservicio-java:latest .

      - name: Docker push
        run: |
          docker push gode23/microservicio-java:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Clonacion del codigo
        uses: actions/checkout@v4

      - name: Despliegue
        run: |
          kubectl apply -f deploy.yaml